version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8002/api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0 --port 5173

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - PORT=8002
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: python app.py

networks:
  app-network:
    driver: bridge 