services:
  - type: web
    name: ai-powered-food-visualization-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: PORT
        value: 8002

  - type: web
    name: ai-powered-food-visualization-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ai-powered-food-visualization-backend.onrender.com/api 